### ISSUE TITLE
[BUG] formParameters and Named Parameters not correct for the method

### ISSUE THREAD

**Issue by CozyLife** [alecsammon/php-raml-parser#56]
**The Problem**
When creating a method which utilizes the "body" parameter, [\Raml\Method::createFromArray()](https://github.com/alecsammon/php-raml-parser/blob/master/src/Method.php#L132) checks for valid types. If the valid type exists, then it sets the valid type as a key, and  passes its contents to [\Raml\WebFormBody::createFromArray()](https://github.com/alecsammon/php-raml-parser/blob/master/src/WebFormBody.php#L8), an alias for [\Raml\NamedParameter::createFromArray()](https://github.com/alecsammon/php-raml-parser/blob/master/src/NamedParameter.php#L216).

The NamedParameter class is intended to process data for a named parameter as described in the [RAML 0.8 spec for Named Parameters](http://raml.org/spec.html#named-parameters). However, the RAML format specifies an extra entry of "formParameters" after the "body" token's valid media types, and before a named parameter even shows up as defined by the spec. (See [Named Parameters with Multiple Types](http://raml.org/spec.html#named-parameters-with-multiple-types))

Also, the Named Parameter should use the key for each named parameter, not the valid media type as a key. The valid media type doesn't implement the same data structure as a Named Parameter, so even omitting the "formParameters" token doesn't allow for parsing any Named Parameters.
```
#%RAML 0.8
title: Amazon simple storage API
version: 1
baseUri: https://{destinationBucket}.s3.amazonaws.com
/:
  post:
    description: The POST operation adds an object to a specified bucket using HTML forms.
    body:
      application/x-www-form-urlencoded:
        formParameters:
          AWSAccessKeyId:
            description: The AWS Access Key ID of the owner of the bucket who grants an Anonymous user access for a request that satisfies the set of constraints in the Policy.
            type: string
          acl:
            description: Specifies an Amazon S3 access control list. If an invalid access control list is specified, an error is generated.
            type: string
          file:
            - type: string
              description: Text content. The text content must be the last field in the form.
            - type: file
              description: File to upload. The file must be the last field in the form.
```

**Proposed Solution**
Create \Raml\WebFormBody::createFromArray() and have it loop over each named parameter and run \Raml\NamedParameter::createFromArray(). Store each named parameter in a private array local to the \Raml\WebFormBody class, and have a getter/setter method to add and retrieve named parameters.

Therefore, the code:

```
\V1\RAML::parse()->getResourceByUri('/')->getMethod('POST')->getBodyByType('application/x-www-form-urlencoded')->getNamedParameters();
```
Should return an array of \Raml\NamedParameter objects to work with.
