### ISSUE TITLE
Bad parsing of SecuritySchemas

### ISSUE THREAD

**Issue by rdohms** [alecsammon/php-raml-parser#77]
```
securitySchemes:
  - oauth_2_0: !include external/oauth2.spec.yml
```

This genarates the follwing structure:

```
array (
  0 => 
  array (
    'oauth_2_0' => '!include external/oauth2.spec.yml',
  ),
)
```

So when trying to get the `oauth_2_0` security scheme you are looking in the wrong array and this get the following error.

`Notice: Undefined index: oauth_2_0`

from the `ApiDefinition ->getSecurityScheme ('oauth_2_0') ` call.

Is is possible to get the expected result using

```
securitySchemes:
  oauth_2_0: !include external/oauth2.spec.yml
```

But that is not compatible with the Spec and breaks tools like Mulesoft's Anypoint Platform.

Spec example from docs is: 

```
#%RAML 0.8
title: Dropbox API
version: 1
baseUri: https://api.dropbox.com/{version}
securedBy: [oauth_2_0]
securitySchemes:
    - oauth_2_0: !include oauth_2_0.yml
    - oauth_1_0: !include oauth_1_0.yml
/users:
    get:
        securedBy: [oauth_2_0, oauth_1_0]
```
