### ISSUE TITLE
SecurityScheme->getKey return string(4) "null" instead of NULL

### ISSUE THREAD

**Issue by kernio** [alecsammon/php-raml-parser#93]
**example.raml**
```
#%RAML 0.8

title: Example API
securitySchemes:
    - oauth_2_0: !include oauth_2_0.yml

/api/example/request
  get:
    securedBy: [oauth_2_0, null]
...
```
**testcode.php**
```
$ramlParser = new RamlParser();
foreach ($ramlParser->parse('example.raml', true)->getResources() as $resource) {
          foreach ($resource->getMethods() as $method) {
                $securitySchemes =$method->getSecuritySchemes();
                foreach ($securitySchemes as $scheme) {
                    var_dump($scheme->getKey());
                }
            }
        }
}

```
Result of code execution.
Actual result:
string(9) "oauth_2_0"
string(4) "null"

Expected result:
string(9) "oauth_2_0"
NULL
